# spring.datasource.url=jdbc:mysql://poctesting.mysql.database.azure.com:3306/userdb?authenticationPlugins=com.azure.identity.extensions.mysql.AzureMysqlAuthenticationPlugin&useSSL=true
# spring.datasource.username=springuser
spring.datasource.url=jdbc:mysql://poctesting.mysql.database.azure.com:3306/userdb?sslMode=REQUIRED&serverTimezone=UTC&authenticationPlugins=com.azure.identity.extensions.jdbc.mysql.AzureMysqlAuthenticationPlugin&defaultAuthenticationPlugin=com.azure.identity.extensions.jdbc.mysql.AzureMysqlAuthenticationPlugin
spring.datasource.username=springuser@0c53c388-7eb5-482b-93e5-b18fe1e53cf7
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
logging.level.org.springframework=DEBUG
logging.level.com.azure=DEBUG